import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, UserButton } from "@clerk/nextjs";
import SideBar from "@/components/SideBar";
import NavLink from "@/components/NavLink";
import { links } from "@/constants/links";
import TopBar from "@/components/TopBar";
import NavDrawer from "@/components/NavDrawer";
import StreamVideoProvider from "@/providers/StreamVideoProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <StreamVideoProvider>
            <div className="flex h-full text-white">
              <SideBar />

              <div className="flex-1 flex flex-col  overflow-y-auto ">
                <TopBar />
                <main className="flex-1  p-5">{children}</main>
              </div>
            </div>
          </StreamVideoProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
